FROM nvcr.io/nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-8-jdk
WORKDIR /ort
COPY target/hello-cli/ .
COPY target/classes/ /opt/hello-ort/
CMD ["./bin/hello.sh"]